name: 'Suicide'
description: 'Removes the workflow containing this action from its repository'
author: 'Justin Lopato'
runs:
  using: composite
  steps:
    - run: echo $("${{ github.workflow_ref }}" | sed "s|${{ github.repository }}/||" | cut -d'@' -f1)
      shell: bash
