name: 'Suicide'
description: 'Removes the workflow containing this action from its repository'
author: 'Justin Lopato'
runs:
  using: composite
  steps:
    - run: |
        rm "${{ github.workflow_ref }}" | sed "s|${{ github.repository }}/||" | cut -d'@' -f1
        git commit -m "Remove workflow ${{github.workflow}}"
        git push
      shell: bash
